axonivy/form-editor

- build/Jenkinsfile
- package-lock.json
- package.json
- packages/editor/src/components/editor/Editor.css
- packages/editor/src/components/editor/Editor.tsx
- playwright/.eslintrc.cjs
- playwright/package.json
- playwright/playwright.base.ts
- playwright/tests/custom-reporter.ts
- playwright/tests/page-objects/form-editor.ts
- playwright/tests/page-objects/palette.ts
- playwright/tests/screenshots/assembly.xml
- playwright/tests/screenshots/playwright.config.ts
- playwright/tests/screenshots/pom.xml
- playwright/tests/screenshots/screenshots.spec.ts
- playwright/tests/standalone/editor/palette.spec.ts
- playwright/tests/standalone/playwright.config.ts
- playwright/tsconfig.json
No real integration project yet, so I've added this first e2e test to the main pipeline. Later we should split them into their own integration pipeline.
> XIVY-13128 Add playwright e2e test setup

- packages/editor/src/components/blocks/button/Button.css
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/flex/Flex.css
- packages/editor/src/components/blocks/flex/Flex.tsx
- packages/editor/src/components/blocks/input/Input.css
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/text/Text.css
- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/components/components.ts
- packages/editor/src/components/editor/canvas/Canvas.css
- packages/editor/src/components/editor/canvas/Draggable.css
- packages/editor/src/types/config.ts
- playwright/tests/standalone/editor/palette.spec.ts
- Add button block
- Pimp input block
> XIVY-13128 Blocks

- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/components/editor/ItemDragOverlay.tsx
- packages/editor/src/components/editor/canvas/Draggable.css
- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/components/editor/canvas/DropZone.tsx
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/data/useData.tsx
- packages/editor/src/utils/array.test.ts
- packages/editor/src/utils/array.ts
- General improve the dnd behavior
- Move the data modify stuff from editor and test it
> XIVY-13128 Improve drag and drop behaviour

- packages/protocol/schemaCodegen.cjs
- packages/protocol/src/data/form.ts
the first 'good enough' protocol ... generated from the 'form-tsgen.json' ... which is explicitly designed to feed the form-editor-client protocol generator.
> XIVY-13133 use form-tsgen.json

- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/components/editor/FormToolbar.tsx
- packages/editor/src/components/editor/ItemDragOverlay.tsx
- packages/editor/src/components/editor/canvas/Canvas.tsx
- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/components/editor/data-structure/DataStructure.tsx
- packages/editor/src/components/editor/properties/Properties.tsx
- packages/editor/src/components/editor/properties/PropertyItem.tsx
- packages/editor/src/context/DndContext.tsx
- packages/editor/src/context/useData.tsx
- Refactor dnd context
- Support render components in layout
- Fix resizepanel with order
> XIVY-13133 Refactorings and improvements

- integrations/standalone/src/mock/advanced.f.json
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/blocks/link/Link.tsx
- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/components/editor/Editor.css
- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/components/editor/FormToolbar.tsx
- packages/editor/src/components/editor/canvas/Canvas.css
- packages/editor/src/components/editor/canvas/Canvas.tsx
- packages/editor/src/components/editor/canvas/Draggable.css
- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/components/editor/canvas/DropZone.css
- packages/editor/src/components/editor/properties/Properties.tsx
- packages/editor/src/components/editor/properties/PropertyItem.tsx
- packages/editor/src/components/editor/properties/fields/CheckboxField.tsx
- packages/editor/src/components/editor/properties/fields/InputField.tsx
- packages/editor/src/components/editor/properties/fields/NumberField.tsx
- packages/editor/src/components/editor/properties/fields/SelectField.tsx
- packages/editor/src/components/editor/properties/fields/TextareaField.tsx
- packages/editor/src/context/useData.tsx
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/data/form.ts
- packages/protocol/src/form-client.ts
- Layout component
- 2 Grid modes (2 and 4 Columns)
- Flex mode
- Device simulator (desktop, tablet, mobile)
- Hide padding mode
- Better handling default configs
Core schema change: https://github.com/axonivy/core/pull/5160
> XIVY-13377 Add properties to layout component

- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/components/editor/FormToolbar.tsx
- packages/editor/src/components/editor/canvas/Canvas.tsx
- packages/editor/src/context/useData.tsx
- better handling of undefined data
- only show theme switch toggle if theme context is available
> XIVY-13641 Improvements

- integrations/standalone/src/index.tsx
- integrations/standalone/src/url-helper.ts
- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/components/editor/FormToolbar.tsx
- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/context/useData.tsx
- Add toolbar options menu
Same as on master: https://github.com/axonivy/form-editor-client/pull/54
> XIVY-14079 Add readonly mode > R11.3

- integrations/standalone/src/index.tsx
- integrations/standalone/src/url-helper.ts
- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/components/editor/FormToolbar.tsx
- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/context/useData.tsx
- Add toolbar options menu (for theme, helper paddings, data source)
> XIVY-14079 Add readonly mode

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
see the odd package-lock.json under https://github.com/axonivy/form-editor-client/pull/59/files
> 11.3: manually fix package-lock after update:axonivy:next

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/editor/FormToolbar.tsx
I'm currently still using the wrong icons for mobile/tablet. I'll wait with the merge of this PR until Anais gives me the new icons.
> XIVY-13261 Adopt Toolbar DeviceToggle and Help-Padding-Switch

- integrations/standalone/src/index.tsx
- integrations/standalone/src/mock.tsx
- packages/editor/src/App.tsx
- packages/editor/src/components/editor/Editor.tsx
- packages/protocol/src/data/form-data.ts
if not set, `false` get passed to server
> XIVY-14104 add optional directSave flag

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/components.ts
- packages/editor/src/components/editor/FormToolbar.tsx
- packages/editor/src/components/editor/palette/PaletteCategoryPopup.tsx
- packages/editor/src/components/editor/properties/Properties.tsx
- packages/editor/src/types/config.ts
- playwright/tests/standalone/editor/palette.spec.ts
I added the following improvements:
- Add EmptyDetail-Component from UI-Components
- Add Chevron to Components-Popup
- Add responsiveness to Components-Popup (if not enough space only show "All Components")
> XIVY-13261 Improve responsive-toolbar / add arrow-icon / add emptyDetail

- packages/editor/src/components/blocks/button/Button.css
- packages/editor/src/components/blocks/input/Input.css
- packages/editor/src/components/editor/canvas/Canvas.css
- packages/editor/src/components/editor/canvas/Draggable.css
I have adopted the canvas design (as best as possible) analogue to the mock-up. Have I forgotten anything?
The only thing I have (deliberately) not adopted is the fill colour of the input fields. I'm not sure whether this makes sense the way Anais designed it, as the default input field is always white, what do you think?
> XIVY-13261 Adopt Canvas-Mock

- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/context/DndContext.tsx
- packages/editor/src/context/useData.tsx
Fixed the two Issues from this PR: https://github.com/axonivy/form-editor-client/pull/77
> XIVY-13261 Fix ItemDragOverlay and deselect

- build/Dockerfile.maven
- build/Jenkinsfile
- build/screenshots/Jenkinsfile
build is currently failing because of typescript problem. will be fixed by elio.
> XIVY-13665 Update to Java 21

- integrations/standalone/src/mock/form-client-mock.ts
- integrations/standalone/vite.config.ts
- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/components/editor/properties/PropertyItem.tsx
- packages/editor/src/components/editor/properties/fields/InputField.tsx
- packages/editor/src/components/editor/properties/fields/InputFieldWithBrowser.tsx
- packages/editor/src/components/editor/properties/fields/browser/useAttributeBrowser.tsx
- packages/editor/src/components/editor/properties/fields/browser/variable-tree-data.ts
- packages/editor/src/context/useData.tsx
- packages/editor/src/context/useMeta.ts
- packages/editor/src/query/query-client.ts
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/form-protocol.ts
Based on changes of https://github.com/axonivy/ui-components/pull/125
> XIVY-13130 Add attribute browser

- packages/editor/src/components/editor/FormToolbar.tsx
- packages/editor/src/components/editor/palette/Palette.tsx
- packages/editor/src/components/editor/palette/data-class/DataClassPalette.tsx
- packages/editor/src/components/editor/palette/data-class/data-class-data.test.ts
- packages/editor/src/components/editor/palette/data-class/data-class-data.ts
- packages/editor/src/components/editor/properties/fields/browser/variable-tree-data.test.ts
- packages/editor/src/components/editor/properties/properties-config.ts
> XIVY-13624 Add sub attributes to dataclass palette

- .vscode/launch.json
- integrations/standalone/src/index.tsx
- integrations/standalone/src/url-helper.ts
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/components.ts
- packages/editor/src/editor/palette/data-class/data-class-data.test.ts
- packages/editor/src/editor/palette/data-class/data-class-data.ts
- packages/editor/src/types/config.ts
- Create number input for number type
- Support directSave flag for standalone as url parameter
- Fix: use el expressions for created data values
> XIVY-13624 Support number inputs

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/checkbox/Checkbox.css
- packages/editor/src/components/blocks/checkbox/Checkbox.svg
- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/blocks/link/Link.tsx
- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/components/components.ts
- packages/protocol/schemaCodegen.cjs
- packages/protocol/src/data/form.ts
- playwright/tests/standalone/editor/palette.spec.ts
Here is the first version of the checkbox component. I don't think it's quite finished yet as this was my first try. 
At the moment you can simply control the checked status via a checkbox, but I think it would also make sense here if you could take a boolean value from a data class, right? Also maybe I should add the possiblility to make the checkbox required? I could also add a SelectManyCheckbox (similar to the old FormEditor) to the component.
However, not sure if this is necessary. What do you think?
> XIVY-13643 Add Checkbox-Component

- packages/editor/src/components/components.ts
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/editor/canvas/Canvas.tsx
- packages/editor/src/editor/canvas/data-class/DataClassDialog.tsx
- packages/editor/src/editor/palette/data-class/data-class-data.ts
- packages/editor/src/editor/properties/fields/InputFieldWithBrowser.tsx
First version of create wizard:
> XIVY-13624 Empty form create wizard from data class

- packages/editor/src/components/blocks/select/Select.css
- packages/editor/src/components/blocks/select/Select.svg
- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/components/components.ts
- packages/editor/src/editor/properties/PropertyItem.tsx
- packages/editor/src/editor/properties/fields/InputField.tsx
- packages/editor/src/editor/properties/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/properties/fields/table-field/InputCellWithBrowser.tsx
- packages/editor/src/editor/properties/fields/table-field/SelectTableField.tsx
- packages/editor/src/editor/properties/fields/table-field/TableField.css
- packages/editor/src/editor/properties/fields/table-field/TableField.tsx
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/data/form.ts
- playwright/tests/standalone/editor/palette.spec.ts
I have now completed the Select component. Feedback?
> XIVY-14725: Add select-component

- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/canvas/data-class/DataClassDialog.tsx
> XIVY-13624 Rename data class to data

- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/editor/canvas/Canvas.css
- packages/editor/src/editor/canvas/Canvas.tsx
- packages/editor/src/editor/canvas/DropZone.tsx
Alternative to the delete key:
> Add delete dropzone

- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/data/variable-tree-data.test.ts
- packages/editor/src/data/variable-tree-data.ts
- packages/editor/src/editor/properties/PropertyItem.tsx
- packages/editor/src/editor/properties/fields/InputField.tsx
- packages/editor/src/editor/properties/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/properties/fields/browser/useAttributeBrowser.tsx
- packages/editor/src/types/config.ts
This is my approach on the filter for the Dynamic Options. What do you think? is the findListVariables method to complicated?
> XIVY-14725 Add List-Filter to Attributebrowser

- packages/editor/src/components/blocks/combobox/Combobox.css
- packages/editor/src/components/blocks/combobox/Combobox.svg
- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/components/components.ts
- packages/protocol/src/data/form.ts
I have implemented the first simple version of the combobox.
> XIVY-13642 Add Combobox Component

- .gitignore
- playwright/form-test-project/.gitignore
- playwright/form-test-project/pom.xml
- playwright/form-test-project/src_hd/form/test/project/free/free.rddescriptor
- playwright/form-test-project/src_hd/form/test/project/test/test.rddescriptor
- playwright/playwright.config.ts
- playwright/tests/global.teardown.ts
- playwright/tests/integration/canvas.spec.ts
- playwright/tests/integration/palette.spec.ts
- playwright/tests/integration/url-params.spec.ts
- playwright/tests/page-objects/canvas.ts
- playwright/tests/page-objects/form-editor.ts
- Use neo workspaces on engine level
- Use web ide rest API to create new temp forms
- Cleanup temp forms after test runs if run locally against designer
> XIVY-13649 Create empty temp forms for stable parallel tests

- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/editor/properties/fields/browser/useAttributeBrowser.tsx
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form.ts
Added itemValue, itemLabel and withDropdown properties to Combobox-Component.
> XIVY-13642 Add Properties to Combobox-Component

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/blocks/base.ts
- packages/editor/src/components/blocks/radio/Radio.css
- packages/editor/src/components/blocks/radio/Radio.svg
- packages/editor/src/components/blocks/radio/Radio.tsx
- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/components/components.ts
- packages/protocol/src/data/form.ts
> XIVY-13644 Add Radio-Button to Form-Editor

- packages/editor/src/components/blocks/base.ts
- packages/editor/src/components/blocks/datepicker/DatePicker.css
- packages/editor/src/components/blocks/datepicker/DatePicker.svg
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/components/components.ts
- packages/editor/src/data/variable-tree-data.test.ts
- packages/editor/src/data/variable-tree-data.ts
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/browser/useAttributeBrowser.tsx
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/datepicker.spec.ts
I have created the DatePicker. I have separated Date and Time. If the flag, showTime is selected, the time is also displayed and the corresponding pattern can be defined. What do you think?
> XIVY-13645 Add DatePicker Component to Form-Editor

- packages/editor/src/components/blocks/textarea/Textarea.css
- packages/editor/src/components/blocks/textarea/Textarea.svg
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/components/components.ts
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/textarea.spec.ts
- playwright/tests/page-objects/inscription.ts
- playwright/tests/page-objects/palette.ts
https://github.com/axonivy/core/pull/6608
> XIVY-14814 Add textarea-component to formEditor

- packages/editor/src/components/blocks/radio/Radio.tsx
> XIVY-13644 Add Placeholder for dynamicList / if no Options are defined

- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/blocks/radio/Radio.tsx
- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/types/config.ts
> Reorganise element categories

- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/components/components.ts
- packages/editor/src/types/config.ts
- Improved sorting of Components inside Elements (feedback from Bruno):
- Removed filter from Attributebrowser for Textarea
> XIVY-14814 Add improvements to components

- packages/editor/src/editor/palette/data-class/data-class-data.test.ts
- packages/editor/src/editor/palette/data-class/data-class-data.ts
- playwright/tests/integration/palette.spec.ts
> XIVY-13645 Add depth to data-class-data

- integrations/standalone/src/index.tsx
- package-lock.json
- packages/core/package.json
- packages/core/src/form-client-jsonrpc.ts
- packages/editor/package.json
- packages/editor/src/App.css
https://github.com/axonivy/ui-components/pull/150
> XIVY-14729 Add websocket reconnect

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/blocks/base.ts
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/editor/src/data/logic-tree-data.test.ts
- packages/editor/src/data/logic-tree-data.ts
- packages/editor/src/editor/sidebar/PropertyItem.tsx
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/browser/useAttributeBrowser.tsx
- packages/editor/src/editor/sidebar/fields/browser/useLogicBrowser.tsx
- packages/editor/src/editor/sidebar/fields/table-field/InputCellWithBrowser.tsx
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/form-protocol.ts
Here’s the initial version of the logic-browser.
> XIVY-13131 add first version of logic browser

- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/utils/focus.test.ts
- packages/editor/src/utils/focus.ts
> XIVY-13131 Add autoselect method-parameters

- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/data/data.ts
- packages/editor/src/editor/sidebar/PropertyItem.tsx
- packages/editor/src/editor/sidebar/Sidebar.tsx
- packages/editor/src/editor/sidebar/fields/ColumnsCheckboxField.tsx
- packages/editor/src/types/config.ts
> XIVY-13646 Add Column-Checkbox to DataTable-Properties

- packages/editor/src/components/blocks/composite/fields/Parameters.tsx
- packages/editor/src/editor/sidebar/fields/InputField.tsx
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/NumberField.tsx
- packages/editor/src/editor/sidebar/fields/SelectField.tsx
- packages/editor/src/editor/sidebar/fields/TextareaField.tsx
- packages/editor/src/editor/sidebar/fields/table-field/TableField.tsx
- playwright/tests/integration/properties/button.spec.ts
- playwright/tests/integration/properties/checkbox.spec.ts
- playwright/tests/integration/properties/combobox.spec.ts
- playwright/tests/integration/properties/composite.spec.ts
- playwright/tests/integration/properties/dataTable.spec.ts
- playwright/tests/integration/properties/datepicker.spec.ts
- playwright/tests/integration/properties/input.spec.ts
- playwright/tests/integration/properties/layout.spec.ts
- playwright/tests/integration/properties/link.spec.ts
- playwright/tests/integration/properties/radio.spec.ts
- playwright/tests/integration/properties/select.spec.ts
- playwright/tests/integration/properties/text.spec.ts
- playwright/tests/integration/properties/textarea.spec.ts
- playwright/tests/page-objects/block.ts
- playwright/tests/page-objects/browser.ts
- playwright/tests/page-objects/inscription.ts
- Replace deprecated <Fieldset> with <BasicField>
- Add inscribe method to block page object
> XIVY-13137 Add composite tests

- package-lock.json
- packages/editor/package.json
- packages/editor/src/components/blocks/composite/fields/Parameters.tsx
- packages/editor/src/editor/sidebar/fields/InputField.tsx
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/vite.config.ts
- playwright/form-test-project/pom.xml
- playwright/form-test-project/src_hd/form/test/project/AddressComponent/AddressComponentProcess.p.json
- playwright/form-test-project/src_hd/form/test/project/PersonComponent/PersonComponentProcess.p.json
> XIVY-13137 Add parameter descriptions

- packages/editor/src/components/blocks/datatable/DataTable.css
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/data/data.test.ts
- packages/editor/src/editor/sidebar/fields/datatable-columns/ColumnsCheckboxField.tsx
- packages/editor/src/editor/sidebar/fields/datatable-columns/useDataTableColumns.ts
- packages/protocol/src/data/form.ts
Finally found a good GIF-Tool 😉
> XIVY-13646 Add Paginator, Filter, Sort to DataTable

- packages/editor/src/editor/sidebar/fields/datatable-columns/ColumnsCheckboxField.tsx
> XIVY-13646 Bound children of children... dataTable

- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/data/cms-tree-data.ts
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/TextareaField.tsx
- packages/editor/src/editor/sidebar/fields/browser/useCmsBrowser.tsx
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/form-protocol.ts
> XIVY-13129 Add CMS-Browser to textarea and textBrowser

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/text/Text.tsx
- playwright/tests/integration/properties/button.spec.ts
Hiding icon attribute as feature is not release ready
> XIVY-14809 hides text icon

- packages/editor/src/components/UiBlockHeader.tsx
- packages/editor/src/components/blocks/base.ts
- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/radio/Radio.tsx
- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/protocol/src/data/form.ts
I'm still not really happy with the naming of the checkbox. maybe there is a better label than "Use as Updater".
backend: https://github.com/axonivy/core/pull/6858
> XIVY-13626 Add useAsUpdater-flag

- packages/editor/src/editor/sidebar/fields/condition-builder/Condition.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/ConditionBuilderContext.tsx
- packages/editor/src/editor/sidebar/fields/table-field/TableField.tsx
- playwright/tests/page-objects/behaviourSection.ts
- Updated the ConditionTypes to properly work with EL expressions.
- Added isFalse to ConditionTypes for Boolean
- Enhanced the static options of the Select component to allow adding one empty selection option.
> XIVY-14810 Fix ConditionTypes and enable empty selectOption

- packages/editor/src/editor/FormToolbar.tsx
- playwright/tests/integration/toolbar.spec.ts
- playwright/tests/page-objects/toolbar.ts
- Help paddings to the left and as toggle button
- Device mode to single toggle button
> XIVY-14994 Rearrange toolbar components

- packages/editor/src/components/blocks/input/Input.tsx
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/input.spec.ts
Frontend to: https://github.com/axonivy/core/pull/6925
I have not specifically displayed the decimal places in the canvas. This could at best be added as additionalInfo in the UiBlockHeader. What do you think?
> XIVY-15028 Add Formatting-Section to inputNumber

- packages/editor/src/editor/sidebar/fields/condition-builder/Condition.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/ConditionBuilder.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/ConditionBuilderContext.test.ts
- packages/editor/src/editor/sidebar/fields/condition-builder/ConditionBuilderContext.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/ConditionGroup.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/InputFieldWithConditionBuilder.tsx
- playwright/tests/integration/conditionBuilder.spec.ts
Implement improvements from review: https://1ivy.atlassian.net/browse/XIVY-14810
- Add isEmpty/isNotEmpty as ConditionOperator
- Add always true and always false as ConditionMode next to the Basic and Nested Conditions
> XIVY-14810 Add isEmpty/isNotEmpty and ConditionMode to Builder

- integrations/standalone/src/mock/data-mock.ts
- integrations/standalone/src/mock/form-client-mock.ts
- integrations/standalone/src/mock/validation-mock.ts
- packages/editor/src/components/blocks/composite/fields/Parameters.tsx
- packages/editor/src/components/blocks/composite/fields/StartMethodSelect.tsx
- packages/editor/src/context/AppContext.tsx
- packages/editor/src/context/useValidation.ts
- packages/editor/src/editor/Editor.tsx
- packages/editor/src/editor/canvas/ComponentBlock.css
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/sidebar/Properties.tsx
- packages/editor/src/editor/sidebar/PropertyItem.tsx
- packages/editor/src/editor/sidebar/fields/NumberField.tsx
- packages/editor/src/editor/sidebar/fields/SelectField.tsx
- packages/editor/src/editor/sidebar/fields/TextareaField.tsx
- packages/editor/src/editor/sidebar/fields/table-field/SelectTableField.tsx
- packages/editor/src/editor/sidebar/fields/table-field/TableField.css
- packages/editor/src/editor/sidebar/fields/table-field/TableField.tsx
- packages/editor/src/types/config.ts
- playwright/tests/integration/outline.spec.ts
- playwright/tests/integration/validation.spec.ts
First version of showing validations (only with mock, backend currently has no validation builtin):
> XIVY-13132 Add validations

- build/Jenkinsfile
[try it yourself](https://jenkins.ivyteam.io/job/form-editor-client/job/fix-index-on-jenkins/2/)
> fix index.html on jenkins

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/UiBlockHeader.tsx
- packages/editor/src/context/DndContext.tsx
- packages/editor/src/editor/browser/cms/useCmsBrowser.tsx
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/editor/browser/logic/useLogicBrowser.tsx
- packages/editor/src/editor/canvas/Canvas.css
- packages/editor/src/editor/canvas/ComponentBlock.css
- packages/editor/src/editor/palette/PaletteButton.css
- packages/editor/src/editor/palette/PaletteButton.tsx
- playwright/tests/integration/properties/dataTable.spec.ts
- Disable dnd on preview mode
- Small css improvements
> Feedback from anais

- integrations/standalone/src/mock/data-mock.ts
- integrations/standalone/src/mock/validation-mock.ts
- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/composite/Composite.tsx
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/blocks/link/Link.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
- packages/editor/src/components/blocks/radio/Radio.tsx
- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/editor/src/context/useValidation.ts
- packages/editor/src/editor/sidebar/Sidebar.tsx
- playwright/tests/integration/properties/input.spec.ts
- playwright/tests/integration/validation.spec.ts
- playwright/tests/page-objects/inscription.ts
core: https://github.com/axonivy/core/pull/7080
duplicated ids:
duplicated cids (this is where problems in the editor starts and I think this needs to be solved via f.json):
> XIVY-15183 Add id to inscription

- packages/editor/src/editor/browser/cms/useCmsBrowser.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/InputFieldWithConditionBuilder.tsx
After consultation with bruno, I have changed two icons.
> Fix Icon of CMS-Browser and Condition Builder

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
- packages/editor/src/editor/canvas/Canvas.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/DropZone.css
- packages/editor/src/editor/canvas/EmptyBlock.css
- packages/editor/src/editor/canvas/EmptyBlock.tsx
- Empty canvas full height 
- Change duplicate icon 
- Refactor: empty block
> Whishes from anais

- packages/editor/src/context/AppContext.tsx
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/MasterPart.tsx
- packages/editor/src/editor/data-structure/DataStructure.tsx
- playwright/tests/integration/toolbar.spec.ts
- playwright/tests/page-objects/toolbar.ts
I don't think this should be part of the release...
> XIVY-14844 Remove data structure

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/blocks/link/Link.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/types/config.ts
- playwright/tests/integration/palette.spec.ts
- playwright/tests/integration/properties/composite.spec.ts
- playwright/tests/page-objects/toolbar.ts
> Rename palette labels (add an s)

- playwright/form-test-project/pom.xml
- playwright/playwright.config.ts
- playwright/tests/global.setup.ts
- playwright/tests/page-objects/form-editor.ts
> Fix integration test

- integrations/standalone/package.json
- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/utils/badge-properties.ts
Technically the badges are already typesafe, but only when the are given as prop to the component. This way they are typesafe at the location where the prop objects are written.
> Improve typesafety of badge props

- packages/editor/src/editor/sidebar/fields/table-field/TableField.tsx
- Fix static options validations
> XIVY-13132 Validations

- packages/editor/src/editor/canvas/Canvas.css
- packages/editor/src/editor/canvas/DropZone.css
- packages/editor/src/editor/sidebar/fields/InputField.tsx
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/NumberField.tsx
make empty canvas drop zone full height
> Improve empty canvas block

- integrations/standalone/package.json
- package-lock.json
- package.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- playwright/tests/integration/canvas.spec.ts
- Fix layout duplication by create new cids for child elements
- Copy / Paste elements to selected new target
> XIVY-15631 Copy paste elements

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/datatable/DataTable.css
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/radio/Radio.css
- packages/editor/src/components/blocks/radio/Radio.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- playwright/tests/integration/canvas.spec.ts
- Improve focus elements in canvas (button, datatable column, radio no longer focusable)
- Open inscription when press enter on selected element
> XIVY-15631 Focus element in canvas and open inscription via enter

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/datatable/DataTable.css
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/radio/Radio.css
- packages/editor/src/components/blocks/radio/Radio.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- playwright/tests/integration/canvas.spec.ts
- Improve focus elements in canvas (button, datatable column, radio no longer focusable)
master https://github.com/axonivy/form-editor-client/pull/258
> XIVY-15631 Focus element in canvas and open inscription via enter > R12

- integrations/standalone/package.json
- integrations/standalone/src/index.tsx
- integrations/standalone/src/mock.tsx
- package-lock.json
- package.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/MasterPart.tsx
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/sidebar/Sidebar.tsx
- playwright/tests/integration/toolbar.spec.ts
- playwright/tests/page-objects/toolbar.ts
Global
- D: open dataclass
- P: open process
- F1: open help
- S: Device Mode
- E: View Mode
- A: Create from data
On element:
- M: duplicate element
> XIVY-15631 Add shortcuts

- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/sidebar/Sidebar.tsx
hotkeyText uses window variable. This should not be used in a global code, but only inside of react stuff. Otherwise neo cannot build it's ssr mode
> XIVY-15631 Fix help texts

- integrations/standalone/package.json
- integrations/standalone/src/index.tsx
- integrations/standalone/src/mock.tsx
- integrations/standalone/src/mock/form-client-mock.ts
- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/MasterPart.tsx
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/sidebar/Properties.tsx
- packages/editor/src/editor/sidebar/Sidebar.tsx
- packages/editor/src/utils/hotkeys.ts
- playwright/tests/integration/toolbar.spec.ts
- playwright/tests/page-objects/inscription.ts
- playwright/tests/page-objects/toolbar.ts
- playwright/tests/screenshots/editor.spec.ts
Global
- D: open dataclass
- P: open process
- F1: open help
- S: Device Mode
- E: View Mode
- A: Create from data
- Alt+(1-3): Jump focus to toolbar, canvas, inscription
On element:
- M: duplicate element
master: 
- https://github.com/axonivy/form-editor-client/pull/265
- https://github.com/axonivy/form-editor-client/pull/267
- https://github.com/axonivy/form-editor-client/pull/268
- https://github.com/axonivy/form-editor-client/pull/269
> XIVY-15631 Add shortcuts > R12

- integrations/standalone/src/mock.tsx
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- playwright/tests/integration/canvas.spec.ts
- playwright/tests/integration/url-params.spec.ts
- playwright/tests/page-objects/block.ts
- View mode
- Create from data
- Duplicate element
- Copy/Paste elements
master: https://github.com/axonivy/form-editor-client/pull/270
> XIVY-15631 Disable shortcuts in readonly editor > R12

- packages/editor/src/utils/hotkeys.ts
- playwright/tests/integration/toolbar.spec.ts
https://github.com/axonivy/form-editor-client/pull/273
> XIVY-15631 Change focus jump shortcut to 1-3 without alt > R12

- integrations/standalone/package.json
- integrations/standalone/src/index.tsx
- integrations/standalone/src/mock.tsx
- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
https://github.com/axonivy/form-editor-client/pull/275
> XIVY-15631 Fix disable hotkeys > R12

- integrations/standalone/src/mock/data-mock.ts
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/editor/canvas/drag-data.test.ts
- packages/editor/src/editor/canvas/drag-data.ts
- Do not allow to drag new elements into data table
- Do not allow to copy/paste other elements into data table
> XIVY-15863 Prevent other things than columns in table

- packages/editor/src/data/data.ts
Revert when XIVY-15872 is solved
> XIVY-15863 Fix DataTableColumn has no type

- integrations/standalone/package.json
- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
- packages/editor/src/editor/sidebar/Sidebar.tsx
- packages/editor/src/utils/hotkeys.ts
- playwright/tests/integration/canvas.spec.ts
- playwright/tests/integration/toolbar.spec.ts
https://github.com/axonivy/form-editor-client/pull/285
> Redo hotkey > R12

- integrations/standalone/package.json
- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/editor/browser/Browser.tsx
- packages/editor/src/editor/browser/condition-builder/condition-builder-data.ts
https://github.com/axonivy/form-editor-client/pull/291
> Adapt condition builder > R12

- integrations/standalone/vite.config.ts
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/button/IconField.tsx
- packages/editor/src/components/blocks/datatable/fields/ListItemWithActions.tsx
- packages/editor/src/components/blocks/datatablecolumn/ActionButtonsField.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/editor/Editor.tsx
> XIVY-15035 Add Icons to Button-Component

- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/layout.spec.ts
- Add poss. to use 1-Column-Grid-Layout
- Add poss. to configure align-items on Layout
https://github.com/axonivy/core/pull/8024
> XIVY-16149 Improve layout possibilities of Layout-Component

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/layout.spec.ts
Cherry-Pick for r12 from master
> R12 imp layout button

- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
> XIVY-15035 Improve visual of Menu Button in Action Column

- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
> XIVY-16035 Add UiBadge to DataTableColumn-Header

- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/editor/sidebar/PropertyItem.tsx
- packages/editor/src/editor/sidebar/fields/ToggleGroupField.tsx
- packages/editor/src/types/config.ts
- playwright/tests/integration/properties/layout.spec.ts
- playwright/tests/page-objects/inscription.ts
I integrated the toggle group. What do you think? Should i apply it this way?
> XIVY-16149 Use ToggleGroup for Layout-Position-Config

- integrations/standalone/package.json
- package-lock.json
- package.json
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/editor/sidebar/PropertyItem.tsx
- packages/editor/src/editor/sidebar/fields/SelectField.tsx
- packages/editor/src/editor/sidebar/fields/ToggleGroupField.tsx
- packages/editor/src/types/config.ts
- playwright/tests/integration/properties/layout.spec.ts
- playwright/tests/page-objects/inscription.ts
what would you think if we solved this alignment with buttongroups (analogue figma)?
> XIVY-16149 Rename Layout-Positioning-Options and add icons

- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/composite/fields/Parameters.tsx
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/link/Link.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/editor/src/editor/browser/Browser.tsx
- packages/editor/src/editor/browser/browser.test.ts
- packages/editor/src/editor/browser/cms/AddCmsQuickFix.tsx
- packages/editor/src/editor/browser/cms/useTextSelection.test.ts
- packages/editor/src/editor/browser/cms/useTextSelection.ts
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/TextareaField.tsx
- packages/editor/src/editor/sidebar/fields/table-field/InputCellWithBrowser.tsx
- packages/editor/src/types/config.ts
- Improve how/where Browser-Options are defined
@ivy-lli fyi - Cherry-Pick: https://github.com/axonivy/form-editor-client/pull/385
> XIVY-16015 Add Attribute Browser to Text-Component

- packages/editor/src/editor/browser/data-class/variable-tree-data.test.ts
- packages/editor/src/editor/browser/data-class/variable-tree-data.ts
https://github.com/axonivy/form-editor-client/pull/409
> XIVY-16199 Load attributes deep until recursion > R12

- integrations/standalone/src/mock.tsx
- integrations/standalone/src/url-helper.ts
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.ts
- packages/editor/src/components/blocks/dialog/Dialog.tsx
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/useComponentBlockActions.ts
> XIVY-15034 Make "Create Workflow Button"-Checkbox optional

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/button/fields/IconField.tsx
- packages/editor/src/components/blocks/button/fields/TypeField.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/components/components.ts
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/sidebar/PropertyItem.tsx
- packages/protocol/src/data/form-data.ts
- playwright/tests/integration/properties/dataTable.spec.ts
- playwright/tests/page-objects/block.ts
- Add/Delete "Edit" & "Delete" Button from editable Datatable
- Always render "Add"-Button on last row of editable Datatable
- Add tests
https://github.com/axonivy/core/pull/8346
> XIVY-15034 Improve ActionButtons on editable Table

- packages/editor/src/components/blocks/datatable/DataTable.css
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/blocks/radio/Radio.css
- Make Label of Dialog-Components visible
- Do not show Dialog in preview-mode
- Ensure gap is the same for every component with label
> XIVY-16149 Improve styling

- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/combobox/Combobox.css
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.test.ts
- packages/editor/src/components/blocks/datepicker/DatePicker.css
- packages/editor/src/components/blocks/input/Input.css
- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/blocks/radio/Radio.css
- packages/editor/src/components/blocks/select/Select.css
- packages/editor/src/components/blocks/textarea/Textarea.css
- packages/editor/src/editor/canvas/DropZone.css
- packages/editor/src/editor/sidebar/property.test.ts
- packages/editor/src/editor/sidebar/property.ts
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/layout.spec.ts
- Remove Vertical Alignment on Layout-Component
https://github.com/axonivy/core/pull/8372
> XIVY-16149 Add AlignSelf to all Components

- integrations/standalone/src/mock/data-mock-datatable.ts
- integrations/standalone/src/mock/data-mock.ts
- packages/editor/src/components/blocks/composite/Composite.tsx
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.test.ts
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/context/AppContext.tsx
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/MasterPart.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/useComponentBlockActions.test.ts
- packages/editor/src/editor/canvas/useComponentBlockActions.ts
- packages/editor/src/editor/sidebar/Properties.tsx
- packages/editor/src/editor/sidebar/Sidebar.tsx
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form.ts
- packages/protocol/src/defaults/config.ts
- packages/protocol/src/form-protocol.ts
- playwright/tests/integration/toolbar.spec.ts
- playwright/tests/page-objects/inscription.ts
- Do not close sidebar if click outside the canvas/component
- Close/Open sidebar on doubleclick outside the canvas/component
https://github.com/axonivy/core/pull/8456
> XIVY-14831 Add FormConfig-FormType-Sidebar

- integrations/standalone/package.json
- package-lock.json
- package.json
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
Fixes the width issue of the "InputFieldWithBrowser" with long values.
> XIVY-16414 fixes the width of the inputfield wit long values

- integrations/standalone/src/mock/data-mock-datatable.ts
- integrations/standalone/src/mock/data-mock.ts
- packages/editor/src/components/blocks/composite/Composite.tsx
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.test.ts
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/context/AppContext.tsx
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/MasterPart.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/useComponentBlockActions.test.ts
- packages/editor/src/editor/canvas/useComponentBlockActions.ts
- packages/editor/src/editor/sidebar/Properties.tsx
- packages/editor/src/editor/sidebar/Sidebar.tsx
- packages/editor/src/translation/form-editor/en.json
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form.ts
- packages/protocol/src/defaults/config.ts
- packages/protocol/src/form-protocol.ts
- playwright/tests/integration/toolbar.spec.ts
- playwright/tests/page-objects/inscription.ts
Cherry-Pick current state of the ivy-component feature to r12
> R12 ivy component feature

- packages/editor/src/components/blocks/composite/Composite.tsx
https://github.com/axonivy/core/pull/8576
> XIVY-14831 Fix Preview if Composite is not a Ivy-Component

- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/button/fields/TypeField.tsx
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.test.ts
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.ts
- packages/editor/src/translation/form-editor/de.json
- packages/editor/src/translation/form-editor/en.json
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form.ts
> XIVY-16543 Add Confirm-Dialog to Delete-Button

- integrations/standalone/src/mock/form-client-mock.ts
- packages/editor/src/context/AppContext.tsx
- packages/editor/src/editor/Editor.tsx
- packages/editor/src/editor/browser/extract/ExtractComponentDialog.tsx
- packages/editor/src/editor/browser/extract/useExtractFieldValidation.test.ts
- packages/editor/src/editor/browser/extract/useExtractFieldValidation.ts
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/useComponentBlockActions.test.ts
- packages/editor/src/editor/canvas/useComponentBlockActions.ts
- packages/editor/src/test-utils/test-utils.tsx
- packages/editor/src/translation/form-editor/de.json
- packages/editor/src/translation/form-editor/en.json
- packages/protocol/src/data/form.ts
- packages/protocol/src/form-protocol.ts
- playwright/tests/integration/properties/button.spec.ts
- playwright/tests/integration/properties/layout.spec.ts
https://github.com/axonivy/core/pull/8709
>  XIVY-16548 Extend Extract-Layout-Action to include namespace/field

- integrations/standalone/src/index.css
- packages/editor/src/App.css
- packages/editor/src/App.tsx
- packages/editor/src/editor/Editor.tsx
- packages/protocol/src/data/form-data.ts
https://github.com/axonivy/form-editor/pull/498
> Move ui-components/icons css to integration

- packages/editor/src/components/blocks/button/Button.css
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.test.ts
- packages/editor/src/translation/form-editor/de.json
- packages/editor/src/translation/form-editor/en.json
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/button.spec.ts
- Add additional button variant options (success, info, etc.)
- Enable switching between solid, outline and flat style
- Add option to apply rounded edges to buttons
https://github.com/axonivy/core/pull/8749
> XIVY-16228 Enhance Button Component for Flexible Styling

- packages/editor/src/components/UiBlockHeader.css
- packages/editor/src/components/UiBlockHeader.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/utils/badge-properties.test.tsx
- packages/editor/src/utils/badge-properties.tsx
- playwright/tests/integration/properties/dataTable.spec.ts
- Remove "ivyFormDataTable.currentRow."-Prefix from Badge
- Fix DataTable-Preview if Filtering is active
- Fix display of Behaviour-Header-Buttons
> XIVY-16543 Fix minor UI-Bugs

- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
@ivy-lli fyi: cherry-pick to 12
> XIVY-16548 Enable also Panel & Fieldset to be extracted into a component

- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/button.spec.ts
- playwright/tests/integration/properties/dataTable.spec.ts
- playwright/tests/page-objects/block.ts
https://github.com/axonivy/core/pull/8771
> XIVY-16543 Allow horizontal alignment of Action-Button in Column

- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/composite/fields/Parameters.tsx
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/editor/browser/Browser.tsx
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.test.ts
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/editor/browser/data-class/variable-tree-data.test.ts
- packages/editor/src/editor/browser/data-class/variable-tree-data.ts
- packages/editor/src/editor/browser/extract/ExtractComponentDialog.tsx
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/button.spec.ts
- playwright/tests/integration/properties/dataTable.spec.ts
- playwright/tests/integration/properties/layout.spec.ts
- playwright/tests/page-objects/block.ts
@ivy-lli fyi: Cherry-Pick to 12
> R12 latest feature table component

- packages/editor/src/editor/FormToolbar.tsx
- playwright/tests/integration/toolbar.spec.ts
https://github.com/axonivy/form-editor/pull/515
> XIVY-16156 Hide preview button on components > R12

- packages/editor/src/editor/sidebar/fields/table-field/SelectTableField.tsx
- packages/editor/src/editor/sidebar/fields/table-field/TableField.tsx
> XIVY-16406 Make the SelectTableField reorderable

- packages/editor/src/editor/browser/data-class/variable-tree-data.ts
In the previous solution, not all nodes with child-nodes were displayed. Now all necessary fields are displayed.
> XIVY-16548 Improve collectNodesWithChildren to show all nodes with children

- packages/editor/src/components/blocks/button/fields/TypeField.tsx
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.test.ts
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.ts
- packages/editor/src/components/blocks/dialog/Dialog.tsx
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.test.ts
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/utils/badge-properties.test.tsx
- packages/editor/src/utils/badge-properties.tsx
@ivy-lli fyi cherry-pick to 12
> XIVY-16674 Remove ivyFormDataTableHandler prefix from Dialog-Components

- packages/editor/src/components/blocks/button/Button.css
- packages/editor/src/data/data.ts
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
> XIVY-16793 Beautify workflow buttons

- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/table-field/InputCellWithBrowser.tsx
- packages/protocol/src/data/form.ts
> XIVY-16719 Fix InputWithBrowser within editable table

- packages/editor/src/components/blocks/button/Button.css
- packages/editor/src/data/data.ts
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
https://github.com/axonivy/form-editor/pull/544
@ivy-edp fyi
> XIVY-16793 Beautify workflow buttons > R12

- packages/editor/src/data/data.ts
https://github.com/axonivy/form-editor/pull/547
> XIVY-16793 Remove cancel icon > R12

- packages/editor/src/components/UiBlockHeader.css
- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/context/DndContext.tsx
- playwright/form-test-project/src_hd/form/test/project/test/test.f.json
> XIVY-16792 Fix only badges should be italic in preview

- packages/editor/src/components/UiBlockHeader.css
- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/context/DndContext.tsx
https://github.com/axonivy/form-editor/pull/549
> XIVY-16792 Fix only badges should be italic in preview > R12

- packages/editor/src/components/blocks/dialog/Dialog.tsx
> XIVY-16793 Beautify dialog buttons

- packages/editor/src/components/blocks/dialog/Dialog.tsx
https://github.com/axonivy/form-editor/pull/553
> XIVY-16793 Beautify dialog buttons > R12

- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatable/fields/useDataTableColumns.ts
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/editor/browser/data-class/variable-tree-data.test.ts
- packages/editor/src/editor/browser/data-class/variable-tree-data.ts
- packages/editor/src/utils/badge-properties.test.tsx
- packages/editor/src/utils/badge-properties.tsx
https://github.com/axonivy/core/pull/8946
>  XIVY-15968 Enhance SelectItems to support complex El-Expressions

- packages/editor/src/translation/form-editor/de.json
https://github.com/axonivy/form-editor/pull/563
> Translated using Weblate (German)

- packages/editor/src/editor/MasterPart.tsx
- playwright/tests/integration/properties.spec.ts
https://github.com/axonivy/form-editor/pull/577
> XIVY-16892 Close inscription when no selection > R13.1

- packages/editor/src/editor/MasterPart.tsx
- playwright/tests/integration/properties.spec.ts
https://github.com/axonivy/form-editor/pull/577
> XIVY-16892 Close inscription when no selection > R12

- packages/editor/src/editor/browser/data-class/useAttributeBrowser.test.ts
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
> XIVY-15968 Fix attr-browser to correctly handle prefix for root-row

- integrations/standalone/package.json
- package-lock.json
- package.json
- packages/editor/src/components/components.ts
- packages/editor/src/editor/FormToolbar.tsx
- packages/editor/src/editor/sidebar/Properties.tsx
- packages/editor/src/editor/sidebar/fields/TextareaField.tsx
- packages/editor/src/editor/sidebar/property.test.ts
- packages/editor/src/editor/sidebar/property.ts
- packages/editor/src/types/config.ts
- packages/editor/src/utils/array.test.ts
- packages/editor/src/utils/array.ts
- playwright/tests/integration/properties/layout.spec.ts
- playwright/tests/integration/toolbar.spec.ts
- playwright/tests/page-objects/inscription.ts
> XIVY-16851 Change Accordion to InscriptionTabs

- packages/editor/src/context/useValidation.ts
- packages/editor/src/editor/sidebar/Properties.tsx
- playwright/tests/integration/properties/button.spec.ts
- playwright/tests/page-objects/inscription.ts
> XIVY-16851 Add State-Dots to Collapsible and InscriptionTabs

- integrations/standalone/package.json
- package-lock.json
- package.json
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
- packages/editor/src/editor/browser/extract/ExtractComponentDialog.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/useComponentBlockActions.ts
- playwright/tests/integration/properties/layout.spec.ts
https://github.com/axonivy/dataclass-editor/pull/459
> XIVY-17023 Disable hotkey scope 'global' if dialog is open

- integrations/standalone/src/mock/form-client-mock.ts
- integrations/standalone/src/mock/meta-mock.ts
- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatable/fields/useDataTableColumns.ts
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/dialog/Dialog.tsx
- packages/editor/src/editor/browser/Browser.tsx
- packages/editor/src/editor/browser/data-class/DataClassDialog.tsx
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.test.ts
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/editor/browser/data-class/variable-tree-data.test.ts
- packages/editor/src/editor/browser/data-class/variable-tree-data.ts
- packages/editor/src/editor/browser/extract/ExtractComponentDialog.tsx
- packages/protocol/src/data/form.ts
- packages/protocol/src/form-protocol.ts
- playwright/tests/integration/properties/dataTable.spec.ts
https://github.com/axonivy/core/pull/9738
> XIVY-16223 Enhanced Attribute-Meta to get VariableInfos of Generic (for DataTable with Repo)

- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/translation/form-editor/de.json
- packages/editor/src/translation/form-editor/en.json
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/data/form-defaults.ts
- packages/protocol/src/data/form.ts
- playwright/tests/page-objects/behaviourSection.ts
- playwright/tests/page-objects/inscription.ts
https://github.com/axonivy/core/pull/9898
> XIVY-16014 Add Listener-Property to UpdateComponent

- .vscode/settings.json
- form-editor.code-workspace
https://github.com/axonivy/neo/pull/756
> Fix ide lint > R12

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/translation/form-editor/en.json
> XIVY-16014 Rename Action & Listener Field

- packages/editor/src/editor/browser/extract/ExtractComponentDialog.tsx
- packages/editor/src/translation/form-editor/de.json
- packages/editor/src/translation/form-editor/en.json
This restriction is no longer needed, since extracting a datatable should now work
> XIVY-17063 Remove restriction to extract DataTable inside Component
