- build/Jenkinsfile
Remove deleted property 'defaultBranch' form discoverGitReferenceBuild step
> Fix build pipeline

- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/editor/canvas/Canvas.tsx
- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/components/editor/canvas/DropZone.tsx
- packages/editor/src/components/editor/properties/PropertyItem.tsx
- packages/editor/src/context/DndContext.tsx
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/utils/array.test.ts
- packages/editor/src/utils/array.ts
- packages/protocol/src/data/form-data.ts
- Drag new or existing block into or out of a layout block (move element into other elements children section).
- Add some keyboard actions:
- Delete: delete selected element
- ArrowUp: move selected element upwards
- ArrowDown: move selected element downwards
Currently the dnd behaviour inside layouts is not ideal. So I will try to improve this in a followup PR.
> XIVY-13377 Support deep data modification

- integrations/standalone/src/mock/form-client-mock.ts
- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/editor/ItemDragOverlay.tsx
- packages/editor/src/components/editor/canvas/Canvas.css
- packages/editor/src/components/editor/canvas/Canvas.tsx
- packages/editor/src/components/editor/canvas/Draggable.css
- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/components/editor/canvas/DropZone.css
- packages/editor/src/components/editor/canvas/DropZone.tsx
- packages/editor/src/components/editor/canvas/drag-data.test.ts
- packages/editor/src/components/editor/canvas/drag-data.ts
- packages/editor/src/components/editor/palette/Palette.tsx
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/protocol/src/data/form-data.ts
- Improve the dnd behavior
- disable all included dropzones for a layout component (it makes no sense to drop a layout into itself :D)
- disable dropzone for the previous element (as this change has no effect to the order)
- Update the design a bit
- enable scroll for big forms
> XIVY-13377 Improve layout dnd behavior

- packages/editor/src/components/blocks/base.ts
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/blocks/link/Link.tsx
- packages/editor/src/components/blocks/text/Text.tsx
- packages/editor/src/components/editor/properties/Properties.tsx
- packages/editor/src/types/config.ts
I have built the subsections into the form editor. Currently they are all in the General section. What kind of subsections there should be is better dealt with in a separate story.
What do you think of this solution?
At the moment all collapsibles are always open, I have not yet implemented the same behaviour as with the inscription view (if everything is configured, the collapsible is closed or the status circle at the collapsible trigger). Should I try to implement that in this story as well? I think the whole undo and data handling is not quite as advanced as with the Inscription View and could therefore be a bit more work.
> XIVY-13261 Add Subsections to the Properties

- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/components/editor/palette/PaletteItem.tsx
- packages/editor/src/utils/useDraggableOverWidth.ts
If you now drag a component from the toolbar into the canvas, a preview of the actual component is displayed directly. In addition, the overlay width now adapts to the effective width that it will need later.
> XIVY-13261 Improve Overlay

- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/editor/canvas/Canvas.css
- packages/editor/src/components/editor/canvas/Canvas.tsx
- packages/editor/src/context/DndContext.tsx
I have managed to "remove" the DropZone, or rather I have made it so small that the user cannot see it. To ensure that the dnd still works, I had to adjust the collision detection algorithm slightly. For most cases, the pointerWithin is still used, but a mix between rectIntercept and pointerWithin is used to detect the canvas drop zone. 
This approach has the advantage that I can leave everything else (add-mechanisms/dropzones etc.) as it is. It works quiet good this way (see GIF). What do you think?
> XIVY-13261 Improve Collision detection algorithm

- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/context/DndContext.tsx
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
I'm not quite sure if this is so elegant to simply return newComponentId as another object via modifyData, as I still have to do ".newData" when calling the method.
> Improve selected when inserted

- package-lock.json
- packages/core/package.json
- packages/editor/package.json
- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/components/blocks/layout/Layout.tsx
- packages/editor/src/components/editor/Editor.tsx
- packages/editor/src/components/editor/FormToolbar.tsx
- packages/editor/src/components/editor/canvas/Canvas.css
- packages/editor/src/components/editor/canvas/Canvas.tsx
- packages/editor/src/components/editor/canvas/Draggable.css
- packages/editor/src/components/editor/canvas/Draggable.tsx
- packages/editor/src/components/editor/canvas/DropZone.css
- packages/editor/src/components/editor/canvas/DropZone.tsx
- packages/editor/src/components/editor/properties/Properties.tsx
- packages/editor/src/context/DndContext.tsx
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
In this PR I have improved the following things:
- Design layout component: It is now (hopefully) a bit clearer where the different boxes are in the grid.
- If the canvas is still empty, an Empty hint appears
- If the layout is still empty, an empty hint appears
- If no element is selected, the properties sidebar closes and if one is selected, it opens
- If an element is dropped to a new location, it remains selected. If an element is dragged into the canvas, it is selected immediately. (The only thing that does not yet work there is when a new element is dragged into a layout component. I would look at this in another PR)
> Improve layout and empty state

- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
I have incorporated the feedback from bruno and set the default of the selected-property to "true".
https://1ivy.atlassian.net/jira/software/c/projects/XIVY/boards/49?quickFilter=247&selectedIssue=XIVY-13643
I have also added a small interaction, if you enter "false", you can see what the unselected checkbox looks like. You don't really need it, but it wasn't too much work and I thought it might be cool if you can do it.
> XIVY-13643 Improve Checkbox

- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/data/variable-tree-data.test.ts
- packages/editor/src/data/variable-tree-data.ts
- packages/editor/src/editor/properties/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/properties/fields/browser/useAttributeBrowser.tsx
- packages/editor/src/types/config.ts
I have now created a browser for the dynamic label and value, with which you can find the attributes from the type of the List of Objects selected above. If the field is left empty, the entire object is used (we check in the backend, if empty, the name inside var which is ‘variable’ is used).
> XIVY-14725 Add AttributeBrowser to find attributes of type

- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/radio/Radio.tsx
- packages/editor/src/components/blocks/select/Select.tsx
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/components/components.ts
- Added DatePicker to componentForType for automatic generation via data (toolbar) or 'Create from data'.
- Adjusted descriptions of individual components.
> XIVY-13645 Add DatePicker to createComp. & rename desciptions

- packages/editor/src/components/blocks/base.ts
- packages/editor/src/components/blocks/datatable/DataTable.css
- packages/editor/src/components/blocks/datatable/DataTable.svg
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/components.test.ts
- packages/editor/src/components/components.ts
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/drag-data.ts
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/browser/useAttributeBrowser.tsx
- packages/editor/src/types/config.ts
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/data/form.ts
I implemented the first version of the DataTable component in the form editor. It can:
- Add new columns via quick actions of DataTable
- Move columns within DataTables
- Delete columns via delete or quick action of Column
- Show a button to define a list of objects when the DataTable value is empty (a warning appears if the value is empty)
- Generate columns based on the DataTable-value if something is defined (only show Button if DataTable-value is defined)
- Define column value via browser if a list of objects is set within the DataTable
Open To-Dos:
- Generation doesn’t work for lists of strings or primitive data types
- Column movement across different DataTables should be disabled
- Tests (UT/IT)
> XIVY-13646 Add DataTable-Component

- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/components.ts
- packages/editor/src/data/variable-tree-data.ts
- packages/editor/src/editor/ItemDragOverlay.tsx
- packages/editor/src/editor/sidebar/Properties.tsx
- packages/editor/src/editor/sidebar/fields/browser/useAttributeBrowser.tsx
- packages/protocol/src/data/form-data.ts
- packages/protocol/src/data/form.ts
here is the implementation of the new schema from the backend. 
https://github.com/axonivy/core/pull/6748
In addition, I have added a feature that allows lists of primitive data types (string...) to be selected correctly.
> XIVY-13646 Make Columns of DataTable typesave

- packages/editor/src/components/blocks/datatable/DataTable.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.css
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
I tried to make it so that the height of the header in each column is adjusted simultaneously when a filter is set anywhere. This makes everything look and feel a bit nicer. 
I’m not sure if the way I’ve implemented it is good. What do you think? Maybe it’s overkill, but I wanted to give it a try. However, I’m happy to discard this and keep things as they were to avoid adding too much additional logic.
> XIVY-13646 Control height of all columns

- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/editor/sidebar/fields/datatable-columns/ColumnsCheckboxField.tsx
- packages/editor/src/editor/sidebar/fields/datatable-columns/useDataTableColumns.ts
Previously, when a column was shown/hidden using the checkbox and filterable/sortable options were defined, they were reset. With these changes this is no longer the case.
> XIVY-13646 Hold state of filter-/sortable of Column

- packages/editor/src/components/blocks/base.ts
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/composite/Composite.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/link/Link.tsx
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/browser/useCmsBrowser.tsx
- packages/editor/src/editor/sidebar/fields/table-field/InputCellWithBrowser.tsx
- Improved apply to use '/bla' instead of "/bla" so that the CMS-EL-Expression causes no error during rendering. Final CMS-apply looks like this: #{ivy.cms.co('/bla')}
- Added the CMS-Browser to all Label and Name Properties
> XIVY-13129 Fix CMS-Apply & add Browser to Label-Property

- packages/editor/src/components/blocks/base.ts
- packages/editor/src/editor/sidebar/PropertyItem.tsx
- packages/editor/src/editor/sidebar/fields/InputField.tsx
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/SelectField.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/Condition.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/ConditionBuilder.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/ConditionGroup.tsx
- packages/editor/src/editor/sidebar/fields/condition-builder/InputFieldWithConditionBuilder.tsx
- packages/editor/src/types/config.ts
Here is a first version of the Condition Builder. It can do the following:
- Build normal conditions with two arguments and an operator
- Link multiple conditions together using "and" or "or"
- Group multiple conditions and link these groups using "and/or"
- Pass a single argument and mark it as true
The last feature emerged from a conversation with Bruno, making it unnecessary for him to provide the attribute browser, as the same result can be achieved through the first condition and than the operator "is true".
> Add condition builder

- packages/editor/src/components/blocks/fieldset/Fieldset.css
- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/panel/Panel.css
- packages/editor/src/components/blocks/panel/Panel.tsx
Improved the Fieldset and Panel Component:
- Renamed Checkbox: "Default Collapsed" to "Collaped by default"
- Only show "Collapsed by default" if Collapsible was selected
- Show Minus if "Collapsed by default" is NOT selected and show + if it is
- If "Collapsed by default" is selected don't show content of Fieldset or Panel in Preview-Mode
-
> XIVY-15076 Improve Panel & Fieldset behaviour if defaultCollapsed

- packages/editor/src/data/data.ts
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/data-class/DataClassDialog.tsx
- packages/editor/src/types/config.ts
I improved the quickactions:
- I added to every component the "Create from Data" quickaction
- If it is a "normal" component, the new "Create from Data"-Components are added above
- If it is a Structure-Component (Layout/Fieldset/Panel), the new "Create from Data"-Components are added inside. (The same behaviour was also applied to the "Create"-Action)
- If you use the "Create from Data" from the Toolbar the components are still just added to the end of the canvas
_Quickaction for Datatable_
> XIVY-14893 Add Create from Data to Quickbar & add comp. inside Structure

- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/TextareaField.tsx
- packages/editor/src/editor/sidebar/fields/browser/Browser.tsx
- packages/editor/src/editor/sidebar/fields/browser/useAttributeBrowser.tsx
- packages/editor/src/editor/sidebar/fields/browser/useCmsBrowser.tsx
- packages/editor/src/editor/sidebar/fields/browser/useLogicBrowser.tsx
- packages/editor/src/types/config.ts
- playwright/form-test-project/cms/cms_en.yaml
Before:
After:
Other side effect, meta only requested once (see before, tanstack query count of current data listener, for each browser input filed one)
> Load browser meta not until needed (browser opens)

- integrations/standalone/src/mock/form-client-mock.ts
- integrations/standalone/src/mock/meta-mock.ts
- packages/editor/src/context/useFunction.ts
- packages/editor/src/editor/browser/cms/AddCmsQuickAction.tsx
- packages/editor/src/editor/browser/cms/useCmsBrowser.tsx
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/protocol/src/data/form.ts
- packages/protocol/src/form-protocol.ts
- playwright/tests/integration/properties/input.spec.ts
- playwright/tests/page-objects/inscription.ts
I have now integrated the CMS quick action directly into the input field (it will only be displayed for input fields that have a CMS browser). As soon as something is selected, the popover trigger for the quick actions will be shown.
What's missing is the ability to change the coName of the newly created content object (this was possible with the old quick actions). If this is still desired, I could, for example, implement this in a later PR. What do you think?
> XIVY-15123 Add Cms QuickActions to Input

- playwright/tests/page-objects/inscription.ts
For inexplicable reasons, the selectText() function in firefox did not trigger the CMS quickaction button in the input field. I am now doing the select manually as it seems to work this way. What do you think?
Strangely enough, the IT works for me locally with the previous solution without any problems on all browsers.
> fix IT cmsQuickaction

- packages/editor/src/editor/browser/cms/AddCmsQuickFix.tsx
- packages/editor/src/editor/browser/cms/useTextSelection.test.ts
- packages/editor/src/editor/browser/cms/useTextSelection.ts
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/TextareaField.tsx
- playwright/tests/integration/properties/input.spec.ts
- playwright/tests/page-objects/inscription.ts
After discussing with Bruno, I have now incorporated the following feedback:
- Added the word "CMS-Object" to the CMS Quick Action button to help the user better understand the context.
- Added the CMS Quick Action to the "Content" property (Textarea) of the Text Component as well.
- The CMS Quick Action is now only displayed if the selection does not consist solely of whitespaces, does not contain #{}, and is not surrounded by #{ }.
- I also added some tests for the addCmsQuickAction-utils
> XIVY-15123 Add CMS-Quickaction to Textarea and add other improvements

- packages/editor/src/editor/sidebar/fields/table-field/TableField.css
> Fix badge styles in table

- packages/editor/src/editor/sidebar/fields/InputField.tsx
- playwright/tests/integration/properties/combobox.spec.ts
- playwright/tests/integration/properties/composite.spec.ts
- playwright/tests/integration/properties/datepicker.spec.ts
- playwright/tests/integration/properties/input.spec.ts
- playwright/tests/integration/properties/link.spec.ts
- playwright/tests/page-objects/inscription.ts
I think simple input fields make no sense to have this badge component. If no browser is supported we also don't expect a el expression.
E.g. the name field of a composite is readonly and will not support el expressions:
Other solution would be to add a new field type or only remove it if the field is disabled (but I think this is not good).
> Remove badges from simple inputs

- packages/editor/src/utils/badge-properties.test.tsx
- packages/editor/src/utils/badge-properties.tsx
- removes cms-badge prefix ".../" as it is deemed not needed with tooltip
> XIVY-15526 remove cmsBadge prefix

- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/composite/fields/Parameters.tsx
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/editor/browser/Browser.tsx
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/editor/browser/data-class/variable-tree-data.test.ts
- packages/editor/src/editor/browser/data-class/variable-tree-data.ts
- playwright/tests/integration/properties/composite.spec.ts
Even if this feature was once good ment, it has many false positives:
- requested type `java.lang.Integer`, valid types `Integer`, `Number`, also things like strings etc seems to work
- requested type `String`, valid types `Number`, `Boolean`, etc.
I replaced it with a simple type hint.
> XIVY-15581 Remove type filter from attribute browser

- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- Generate new cid's for columns in copied data table
- Copy paste columns is the same as duplicate, to ensure a column is not copied outside of a table
> XIVY-15631 Fix copy paste data tables and columns

- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- playwright/tests/integration/canvas.spec.ts
same as master https://github.com/axonivy/form-editor-client/pull/257 and https://github.com/axonivy/form-editor-client/pull/260
- Fix layout duplication by create new cids for child elements
- Copy / Paste elements to selected new target
- Generate new cid's for columns in copied data table
- Copy paste columns is the same as duplicate, to ensure a column is not copied outside of a table
> XIVY-15631 Copy paste elements > R12

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/datatable/DataTable.css
- packages/editor/src/components/blocks/layout/Layout.css
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/editor/src/editor/browser/Browser.tsx
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/editor/browser/data-class/variable-tree-data.test.ts
- packages/editor/src/editor/browser/data-class/variable-tree-data.ts
- packages/editor/src/editor/canvas/ComponentBlock.tsx
- packages/editor/src/editor/canvas/DropZone.css
- packages/editor/src/editor/canvas/drag-data.ts
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- Add Attribute-browser to Action-Button
- If text is selected Attr.-Browser replace selection
- Add scrollbar to DataTable if to many columns
Regarding the attribute browser in the action of the button, I have now solved it as follows:
- If something is selected, this selection is replaced with the content of the attribute browser
- If nothing is selected, the content is added to the back (you could possibly make it even smarter by searching for brackets and adding the content to the brackets, for example)
- Something that I still find a little impractical from a UX point of view is that after something has been added via the logic browser, the badge are displayed, you have to click in the action field again, select something and only then can you select the row object via the attribute …
> XIVY-15035 Multiple impr. around DataTableActionButtons

- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/data/data.test.ts
- packages/editor/src/data/data.ts
- packages/protocol/src/data/form.ts
- playwright/tests/integration/properties/button.spec.ts
I added a type field to the button component, defaulting it to "button". For the cancel/proceed buttons, I set the proceed button's type to "submit" to ensure that pressing Enter in the form only triggers the "Proceed" button.
@ivy-lgi, @ivy-rew What do you think? Should I expose the type field in the properties (like I now have via the select) or keep it hidden from users, setting it only to "submit" for the auto-generated "Proceed" button?
https://github.com/axonivy/core/pull/8023
> XIVY-16072 Add Type to Button-Component

- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
I added the Badge component to Fieldset and Panel titles, similar to how it is already used in the Button component:
> XIVY-16035 Add Badges to Fieldset & Panel Titles analog other comp.

- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/editor/browser/data-class/variable-tree-data.ts
With this we could also maybe improve the naming for select/radio to "selectItem" and "radioItem" or just "item" 🤔 
https://github.com/axonivy/core/pull/8055
> XIVY-15035 Rename "variable" for attr-browser of ActionColumn to "row"

- packages/editor/src/components/blocks/base.tsx
- packages/editor/src/components/blocks/button/Button.tsx
- packages/editor/src/components/blocks/checkbox/Checkbox.tsx
- packages/editor/src/components/blocks/combobox/Combobox.tsx
- packages/editor/src/components/blocks/composite/fields/Parameters.tsx
- packages/editor/src/components/blocks/datatable/DataTable.tsx
- packages/editor/src/components/blocks/datatablecolumn/DataTableColumn.tsx
- packages/editor/src/components/blocks/datepicker/DatePicker.tsx
- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/input/Input.tsx
- packages/editor/src/components/blocks/link/Link.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
- packages/editor/src/components/blocks/textarea/Textarea.tsx
- packages/editor/src/editor/browser/Browser.tsx
- packages/editor/src/editor/browser/browser.test.ts
- packages/editor/src/editor/browser/cms/AddCmsQuickFix.tsx
- packages/editor/src/editor/browser/cms/useTextSelection.test.ts
- packages/editor/src/editor/browser/cms/useTextSelection.ts
- packages/editor/src/editor/sidebar/fields/InputFieldWithBrowser.tsx
- packages/editor/src/editor/sidebar/fields/TextareaField.tsx
- packages/editor/src/editor/sidebar/fields/table-field/InputCellWithBrowser.tsx
- packages/editor/src/types/config.ts
For the following story (https://1ivy.atlassian.net/browse/XIVY-16015), I wanted to add an attribute browser to the content input field. Since it's a textarea field, I thought it would make sense for the attribute (and CMS) browser to insert the attribute EL expression at the cursor position instead of replacing the entire value.
However, this required extending the apply function in the browser component with additional if conditions and special cases. That made me wonder: wouldn't it be better to define browser-apply options per browser rather than globally for each input field?
I tried this approach and refactored it so that options are now passed directly in the browser array. What do you think? Does this approach make sense, or is it overkill? Should I revert to the previous …
> Improve browser options

- packages/editor/src/components/blocks/base.tsx
- removes duplicate translation which resulted in undefined behavior:
section gets already translated when it's displayed
https://github.com/axonivy/form-editor-client/blob/25d92ead0c2b423a406f57d51b8f24d37b08e423/packages/editor/src/editor/sidebar/Properties.tsx#L47-L56
> XIVY-16283 removes duplicate translation of layout section

- integrations/standalone/package.json
- package-lock.json
- package.json
- playwright/tests/integration/conditionBuilder.spec.ts
The test started failing after the following change, presumably: https://github.com/axonivy/ui-components/pull/422. Not entirely sure why though.
I will talk to Anaïs about streamlining some design choices regarding dialogs:
- Dialog title and description: I think all dialogs should have a consistent title and description using the components `<DialogHeader>` and `<DialogDescription>`. These are also necessary for accessibility through screen readers.
- Cancel button: Some dialogs have them, some don't. I think this should be consistent. Personally, I vote for removing them.
> fix condition builder tests after browser tab change

- integrations/standalone/src/index.css
- packages/editor/src/App.css
- packages/editor/src/App.tsx
I will take this PR as reference, as I plan to rollout this change to all editor repos.
The reason is, that the ui-icons/ui-components are only peerDependencies on editor level. This means the integration (standalone, vscode, neo) will define the final version for them. 
This means that the output editor.css doesn't need to include the ui-components/ui-icons CSS, as it will also provided by the integration. 
It also means that before it could happen that the editor.css included styles from an old ui-components which didn't match with the current used neo version. Technically this should not make any difference, because the class names are randomized but it could happen that styles are wrong.
So to summarize, this has the effect:
- The editor.css files will be smaller, as the only contain …
> Move ui-components/icons css to integration

- packages/editor/src/components/blocks/fieldset/Fieldset.tsx
- packages/editor/src/components/blocks/panel/Panel.tsx
- packages/editor/src/editor/canvas/ComponentBlock.tsx
feedback from bruno was that he thought it would be useful to be able to extract all structure components (i.e. layout/panel/fieldset) into one ivy component.
> XIVY-16548 Enable also Panel & Fieldset to be extracted into a component

- package-lock.json
- packages/editor/package.json
- packages/editor/src/editor/FormToolbar.tsx
Since React 19, ref can be a prop so forwardRef is no longer needed
> Remove forwardRef API usage

- packages/editor/src/components/blocks/button/fields/TypeField.tsx
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.test.ts
- packages/editor/src/components/blocks/datatable/fields/useEditableDataTableField.ts
- packages/editor/src/components/blocks/dialog/Dialog.tsx
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.test.ts
- packages/editor/src/editor/browser/data-class/useAttributeBrowser.tsx
- packages/editor/src/utils/badge-properties.test.tsx
- packages/editor/src/utils/badge-properties.tsx
https://github.com/axonivy/core/pull/8878
https://github.com/axonivy/core/pull/8893
ToDo: In a later core-pr i will fix the validation errors for "currentRow" (see PrintScreen)
> XIVY-16674 Remove ivyFormDataTableHandler prefix from Dialog-Components

- playwright/tests/integration/properties/layout.spec.ts
For some reason when i press "a" via page.keyboard.press('a') the "Create from Data"-Dialog opens twice. However i can't reproduce the error in the dev environement, so i just remove this part.
> XIVY-16537 Fix shortcut test für firefox

- packages/editor/src/context/useValidation.ts
Previously, there was a bug where, if you had both a dataTable1 and a dataTable14 and a validation with the path dataTable1, the validation messages for dataTable1 would also incorrectly appear on dataTable14.
> XIVY-17063 Fix validation if path startWith similar paths
